//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Events;
using StreamChat.Core.InternalDTO.Models;

namespace StreamChat.Core.InternalDTO.Requests
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal struct CreatePollRequestVotingVisibility : System.IEquatable<CreatePollRequestVotingVisibility>
    {
        public CreatePollRequestVotingVisibility(string value)
        {
            _value = value ?? throw new System.ArgumentNullException(nameof(value));
        }

        public static readonly CreatePollRequestVotingVisibility Anonymous = new CreatePollRequestVotingVisibility("anonymous");
        public static readonly CreatePollRequestVotingVisibility Public = new CreatePollRequestVotingVisibility("public");

        public override string ToString() => _value;

        public bool Equals(CreatePollRequestVotingVisibility other) => _value == other._value;

        public override bool Equals(object obj) => obj is CreatePollRequestVotingVisibility other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(CreatePollRequestVotingVisibility left, CreatePollRequestVotingVisibility right) => left.Equals(right);

        public static bool operator !=(CreatePollRequestVotingVisibility left, CreatePollRequestVotingVisibility right) => !left.Equals(right);

        public static implicit operator CreatePollRequestVotingVisibility(string value) => new CreatePollRequestVotingVisibility(value);

        public static implicit operator string(CreatePollRequestVotingVisibility type) => type._value;
        
        private readonly string _value;
    }
}
