//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Events;
using StreamChat.Core.InternalDTO.Models;

namespace StreamChat.Core.InternalDTO.Requests
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal struct TranslateMessageRequestLanguage : System.IEquatable<TranslateMessageRequestLanguage>
    {
        public TranslateMessageRequestLanguage(string value)
        {
            _value = value ?? throw new System.ArgumentNullException(nameof(value));
        }

        public static readonly TranslateMessageRequestLanguage Af = new TranslateMessageRequestLanguage("af");
        public static readonly TranslateMessageRequestLanguage Sq = new TranslateMessageRequestLanguage("sq");
        public static readonly TranslateMessageRequestLanguage Am = new TranslateMessageRequestLanguage("am");
        public static readonly TranslateMessageRequestLanguage Ar = new TranslateMessageRequestLanguage("ar");
        public static readonly TranslateMessageRequestLanguage Az = new TranslateMessageRequestLanguage("az");
        public static readonly TranslateMessageRequestLanguage Bn = new TranslateMessageRequestLanguage("bn");
        public static readonly TranslateMessageRequestLanguage Bs = new TranslateMessageRequestLanguage("bs");
        public static readonly TranslateMessageRequestLanguage Bg = new TranslateMessageRequestLanguage("bg");
        public static readonly TranslateMessageRequestLanguage Zh = new TranslateMessageRequestLanguage("zh");
        public static readonly TranslateMessageRequestLanguage ZhTW = new TranslateMessageRequestLanguage("zh-TW");
        public static readonly TranslateMessageRequestLanguage Hr = new TranslateMessageRequestLanguage("hr");
        public static readonly TranslateMessageRequestLanguage Cs = new TranslateMessageRequestLanguage("cs");
        public static readonly TranslateMessageRequestLanguage Da = new TranslateMessageRequestLanguage("da");
        public static readonly TranslateMessageRequestLanguage FaAF = new TranslateMessageRequestLanguage("fa-AF");
        public static readonly TranslateMessageRequestLanguage Nl = new TranslateMessageRequestLanguage("nl");
        public static readonly TranslateMessageRequestLanguage En = new TranslateMessageRequestLanguage("en");
        public static readonly TranslateMessageRequestLanguage Et = new TranslateMessageRequestLanguage("et");
        public static readonly TranslateMessageRequestLanguage Fi = new TranslateMessageRequestLanguage("fi");
        public static readonly TranslateMessageRequestLanguage Fr = new TranslateMessageRequestLanguage("fr");
        public static readonly TranslateMessageRequestLanguage FrCA = new TranslateMessageRequestLanguage("fr-CA");
        public static readonly TranslateMessageRequestLanguage Ka = new TranslateMessageRequestLanguage("ka");
        public static readonly TranslateMessageRequestLanguage De = new TranslateMessageRequestLanguage("de");
        public static readonly TranslateMessageRequestLanguage El = new TranslateMessageRequestLanguage("el");
        public static readonly TranslateMessageRequestLanguage Ha = new TranslateMessageRequestLanguage("ha");
        public static readonly TranslateMessageRequestLanguage He = new TranslateMessageRequestLanguage("he");
        public static readonly TranslateMessageRequestLanguage Hi = new TranslateMessageRequestLanguage("hi");
        public static readonly TranslateMessageRequestLanguage Hu = new TranslateMessageRequestLanguage("hu");
        public static readonly TranslateMessageRequestLanguage Id = new TranslateMessageRequestLanguage("id");
        public static readonly TranslateMessageRequestLanguage It = new TranslateMessageRequestLanguage("it");
        public static readonly TranslateMessageRequestLanguage Ja = new TranslateMessageRequestLanguage("ja");
        public static readonly TranslateMessageRequestLanguage Ko = new TranslateMessageRequestLanguage("ko");
        public static readonly TranslateMessageRequestLanguage Lv = new TranslateMessageRequestLanguage("lv");
        public static readonly TranslateMessageRequestLanguage Ms = new TranslateMessageRequestLanguage("ms");
        public static readonly TranslateMessageRequestLanguage No = new TranslateMessageRequestLanguage("no");
        public static readonly TranslateMessageRequestLanguage Fa = new TranslateMessageRequestLanguage("fa");
        public static readonly TranslateMessageRequestLanguage Ps = new TranslateMessageRequestLanguage("ps");
        public static readonly TranslateMessageRequestLanguage Pl = new TranslateMessageRequestLanguage("pl");
        public static readonly TranslateMessageRequestLanguage Pt = new TranslateMessageRequestLanguage("pt");
        public static readonly TranslateMessageRequestLanguage Ro = new TranslateMessageRequestLanguage("ro");
        public static readonly TranslateMessageRequestLanguage Ru = new TranslateMessageRequestLanguage("ru");
        public static readonly TranslateMessageRequestLanguage Sr = new TranslateMessageRequestLanguage("sr");
        public static readonly TranslateMessageRequestLanguage Sk = new TranslateMessageRequestLanguage("sk");
        public static readonly TranslateMessageRequestLanguage Sl = new TranslateMessageRequestLanguage("sl");
        public static readonly TranslateMessageRequestLanguage So = new TranslateMessageRequestLanguage("so");
        public static readonly TranslateMessageRequestLanguage Es = new TranslateMessageRequestLanguage("es");
        public static readonly TranslateMessageRequestLanguage EsMX = new TranslateMessageRequestLanguage("es-MX");
        public static readonly TranslateMessageRequestLanguage Sw = new TranslateMessageRequestLanguage("sw");
        public static readonly TranslateMessageRequestLanguage Sv = new TranslateMessageRequestLanguage("sv");
        public static readonly TranslateMessageRequestLanguage Tl = new TranslateMessageRequestLanguage("tl");
        public static readonly TranslateMessageRequestLanguage Ta = new TranslateMessageRequestLanguage("ta");
        public static readonly TranslateMessageRequestLanguage Th = new TranslateMessageRequestLanguage("th");
        public static readonly TranslateMessageRequestLanguage Tr = new TranslateMessageRequestLanguage("tr");
        public static readonly TranslateMessageRequestLanguage Uk = new TranslateMessageRequestLanguage("uk");
        public static readonly TranslateMessageRequestLanguage Ur = new TranslateMessageRequestLanguage("ur");
        public static readonly TranslateMessageRequestLanguage Vi = new TranslateMessageRequestLanguage("vi");

        public override string ToString() => _value;

        public bool Equals(TranslateMessageRequestLanguage other) => _value == other._value;

        public override bool Equals(object obj) => obj is TranslateMessageRequestLanguage other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(TranslateMessageRequestLanguage left, TranslateMessageRequestLanguage right) => left.Equals(right);

        public static bool operator !=(TranslateMessageRequestLanguage left, TranslateMessageRequestLanguage right) => !left.Equals(right);

        public static implicit operator TranslateMessageRequestLanguage(string value) => new TranslateMessageRequestLanguage(value);

        public static implicit operator string(TranslateMessageRequestLanguage type) => type._value;
        
        private readonly string _value;
    }
}
