//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    public readonly struct AutomodType : System.IEquatable<AutomodType>
    {
        public AutomodType(string value)
        {
            _value = value ?? throw new System.ArgumentNullException(nameof(value));
        }

        public static readonly AutomodType Disabled = new AutomodType("disabled");
        public static readonly AutomodType Simple = new AutomodType("simple");
        public static readonly AutomodType AI = new AutomodType("AI");

        public override string ToString() => _value;

        public bool Equals(AutomodType other) => _value == other._value;

        public override bool Equals(object obj) => obj is AutomodType other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(AutomodType left, AutomodType right) => left.Equals(right);

        public static bool operator !=(AutomodType left, AutomodType right) => !left.Equals(right);

        public static implicit operator AutomodType(string value) => new AutomodType(value);

        public static implicit operator string(AutomodType type) => type._value;
        
        private readonly string _value;
    }
}
