//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum BlockListOptionsBehavior
    {

        [System.Runtime.Serialization.EnumMember(Value = @"flag")]
        Flag = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"block")]
        Block = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"shadow_block")]
        Shadow_block = 2,

    }

}

