//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    public struct ImageCropType : System.IEquatable<ImageCropType>
    {
        public ImageCropType(string value)
        {
            _value = value ?? throw new System.ArgumentNullException(nameof(value));
        }

        public static readonly ImageCropType Top = new ImageCropType("top");
        public static readonly ImageCropType Bottom = new ImageCropType("bottom");
        public static readonly ImageCropType Left = new ImageCropType("left");
        public static readonly ImageCropType Right = new ImageCropType("right");
        public static readonly ImageCropType Center = new ImageCropType("center");

        public override string ToString() => _value;

        public bool Equals(ImageCropType other) => _value == other._value;

        public override bool Equals(object obj) => obj is ImageCropType other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(ImageCropType left, ImageCropType right) => left.Equals(right);

        public static bool operator !=(ImageCropType left, ImageCropType right) => !left.Equals(right);

        public static implicit operator ImageCropType(string value) => new ImageCropType(value);

        public static implicit operator string(ImageCropType type) => type._value;
        
        private readonly string _value;
    }
}
