//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    public struct ImageResizeType : System.IEquatable<ImageResizeType>
    {
        public ImageResizeType(string value)
        {
            _value = value ?? throw new System.ArgumentNullException(nameof(value));
        }

        public static readonly ImageResizeType Clip = new ImageResizeType("clip");
        public static readonly ImageResizeType Crop = new ImageResizeType("crop");
        public static readonly ImageResizeType Scale = new ImageResizeType("scale");
        public static readonly ImageResizeType Fill = new ImageResizeType("fill");

        public override string ToString() => _value;

        public bool Equals(ImageResizeType other) => _value == other._value;

        public override bool Equals(object obj) => obj is ImageResizeType other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(ImageResizeType left, ImageResizeType right) => left.Equals(right);

        public static bool operator !=(ImageResizeType left, ImageResizeType right) => !left.Equals(right);

        public static implicit operator ImageResizeType(string value) => new ImageResizeType(value);

        public static implicit operator string(ImageResizeType type) => type._value;
        
        private readonly string _value;
    }
}
