//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Responses;
using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;

namespace StreamChat.Core.InternalDTO.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    public struct MessageType : System.IEquatable<MessageType>
    {
        public MessageType(string value)
        {
            _value = value ?? throw new System.ArgumentNullException(nameof(value));
        }

        public static readonly MessageType Regular = new MessageType("regular");
        public static readonly MessageType Ephemeral = new MessageType("ephemeral");
        public static readonly MessageType Error = new MessageType("error");
        public static readonly MessageType Reply = new MessageType("reply");
        public static readonly MessageType System = new MessageType("system");
        public static readonly MessageType Deleted = new MessageType("deleted");

        public override string ToString() => _value;

        public bool Equals(MessageType other) => _value == other._value;

        public override bool Equals(object obj) => obj is MessageType other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(MessageType left, MessageType right) => left.Equals(right);

        public static bool operator !=(MessageType left, MessageType right) => !left.Equals(right);

        public static implicit operator MessageType(string value) => new MessageType(value);

        public static implicit operator string(MessageType type) => type._value;
        
        private readonly string _value;
    }
}
