//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;
using StreamChat.Core.InternalDTO.Models;

namespace StreamChat.Core.InternalDTO.Responses
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ChannelMemberResponseRole
    {

        [System.Runtime.Serialization.EnumMember(Value = @"member")]
        Member = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"moderator")]
        Moderator = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"admin")]
        Admin = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"owner")]
        Owner = 3,

    }

}

