//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using StreamChat.Core.InternalDTO.Requests;
using StreamChat.Core.InternalDTO.Events;
using StreamChat.Core.InternalDTO.Models;

namespace StreamChat.Core.InternalDTO.Responses
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]

    internal struct ChannelMemberResponseRole : System.IEquatable<ChannelMemberResponseRole>
    {
        public ChannelMemberResponseRole(string value)
        {
            _value = value ?? throw new System.ArgumentNullException(nameof(value));
        }

        public static readonly ChannelMemberResponseRole Member = new ChannelMemberResponseRole("member");
        public static readonly ChannelMemberResponseRole Moderator = new ChannelMemberResponseRole("moderator");
        public static readonly ChannelMemberResponseRole Admin = new ChannelMemberResponseRole("admin");
        public static readonly ChannelMemberResponseRole Owner = new ChannelMemberResponseRole("owner");

        public override string ToString() => _value;

        public bool Equals(ChannelMemberResponseRole other) => _value == other._value;

        public override bool Equals(object obj) => obj is ChannelMemberResponseRole other && Equals(other);

        public override int GetHashCode() => _value.GetHashCode();

        public static bool operator ==(ChannelMemberResponseRole left, ChannelMemberResponseRole right) => left.Equals(right);

        public static bool operator !=(ChannelMemberResponseRole left, ChannelMemberResponseRole right) => !left.Equals(right);

        public static implicit operator ChannelMemberResponseRole(string value) => new ChannelMemberResponseRole(value);

        public static implicit operator string(ChannelMemberResponseRole type) => type._value;
        
        private readonly string _value;
    }
}
